name: 'Generate GitHub App Token'
description: 'Generates a GitHub App token'
inputs:
  app-id:
    description: 'GitHub App ID'
    required: true
  private-key:
    description: 'GitHub App Private Key'
    required: true

outputs:
  token:
    description: 'Generated GitHub App Token'
    value: ${{ steps.generate-zdc-token.outputs.token }}

runs:
  using: "composite"
  steps:
    - name: Generate GitHub App Token
      uses: actions/create-github-app-token@v1
      id: generate-zdc-token
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        owner: ${{ github.repository_owner }}