name: Deploy Project

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      ZDC_TOKEN:
        required: true
      PASSPHRASE_ACTION_TOKEN:
        required: true

jobs:
  deploy_project_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Decrypt ZDC Token
        id: decrypt-token
        run: |
          ENCRYPTED_TOKEN="${{ secrets.ZDC_TOKEN }}"
          DECRYPTED_TOKEN=$(echo "$ENCRYPTED_TOKEN" | base64 -d | gpg --decrypt --quiet --batch --passphrase "${{ secrets.PASSPHRASE_ACTION_TOKEN }}")
          echo "ZDCTOKEN=$DECRYPTED_TOKEN" >> $GITHUB_ENV
          echo "::add-mask::$DECRYPTED_TOKEN"
      
      - name: Trigger Deployment Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ env.ZDCTOKEN }}
          script: |
            const environment = `"${{ inputs.environment }}"`;
            const project     = `"${{ inputs.project }}"`;
            const workflowId  = `deploy-${environment}.yml`;

            try {
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: project,
                workflow_id: workflowId,
                ref: 'main', // Adjust this if necessary based on branch/ref logic
              });
            } catch (error) {
              core.setFailed(`Failed to trigger the workflow: ${error.message}`);
            }