name: Deploy Project

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      environment:
        required: true
        type: string
      token:
        required: true
        type: string

jobs:
  deploy_project_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ inputs.token }}
          script: |
            const environment = `"${{ inputs.environment }}"`;
            const project     = `"${{ inputs.project }}"`;
            const workflowId  = `deploy-${environment}.yml`;

            try {
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: project,
                workflow_id: workflowId,
                ref: 'main', // Adjust this if necessary based on branch/ref logic
              });
            } catch (error) {
              core.setFailed(`Failed to trigger the workflow: ${error.message}`);
            }