name: Generate Token

on:
  workflow_call:

jobs:
  generate-token:
    runs-on: ubuntu-latest
    outputs:
      zdctoken: ${{ steps.generate-zdc-token.outputs.token }}
    steps:
      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@v1
        id: generate-zdc-token
        with:
          app-id: ${{ vars.ZDC_AUTH_APP_ID }}
          private-key: ${{ secrets.ZDC_AUTH_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Debug Generated Token
        run: |
            echo "Generated Token: ${{ steps.generate-zdc-token.outputs.token }}"