name: Generate Token

on:
  workflow_call:

jobs:
  generate-token:
    runs-on: ubuntu-latest
    outputs:
      ZDC_TOKEN: ${{ steps.encrypt-token.outputs.encrypt-token }}
    steps:
      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@v1
        id: generate-zdc-token
        with:
          app-id: ${{ vars.ZDC_AUTH_APP_ID }}
          private-key: ${{ secrets.ZDC_AUTH_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Encrypt and Encode Token
        id: encrypt-token
        run: |
          TOKEN="${{ steps.generate-zdc-token.outputs.token }}"
          ENCRYPTED_TOKEN=$(echo -n "$TOKEN" | gpg --symmetric --quiet --batch --passphrase "${{ secrets.PASSPHRASE_ACTION_TOKEN }}" | base64 -w0)
          echo "ZDC_TOKEN=$ENCRYPTED_TOKEN" >> $GITHUB_OUTPUT