name: Notify User

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      project:
        required: true
        type: string
      infra:
        required: true
        type: string

jobs:
  notify-user:
    name: Notify user
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Notify User
        uses: actions/github-script@v7
        with:
          script: |
            const environment = `"${{ inputs.environment }}"`;
            const project     = `"${{ inputs.project }}"`;
            const infra       = `"${{ inputs.infra }}"`;

            const { default: notifyUser } =
              await import(`${{ github.workspace }}/actions_scripts/notify_user.js`);

            return await notifyUser({github, context, core, environment, project, infra});